version: '3'
services:
    npm:
        image: node:9.11.1-alpine
        entrypoint: npm
        working_dir: /src
        volumes:
            - "./:/src"
    test:
        image: node:9.11.1-alpine
        entrypoint: npm
        command: test
        working_dir: /src
        volumes:
            - "./:/src"
